"""Feedback table

Revision ID: 710a64380619
Revises: d427a38b25c6
Create Date: 2024-01-24 12:45:55.529950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '710a64380619'
down_revision: Union[str, None] = 'd427a38b25c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('donor_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('donation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['passengers.id'], name='charity_donor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='charity_pkey')
    )
    # ### end Alembic commands ###
