"""Fields change  migration

Revision ID: 80ceaf70ba38
Revises: 329f5d5b42cb
Create Date: 2024-01-13 18:18:11.893529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ceaf70ba38'
down_revision: Union[str, None] = '329f5d5b42cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('drivers_registration_number_key', 'drivers', type_='unique')
    op.drop_column('drivers', 'nickname')
    op.drop_column('drivers', 'registration_number')
    op.drop_constraint('passengers_registration_number_key', 'passengers', type_='unique')
    op.drop_column('passengers', 'registration_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengers', sa.Column('registration_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint('passengers_registration_number_key', 'passengers', ['registration_number'])
    op.add_column('drivers', sa.Column('registration_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('nickname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint('drivers_registration_number_key', 'drivers', ['registration_number'])
    # ### end Alembic commands ###
