"""Rating table

Revision ID: e2e5bf1f9095
Revises: 710a64380619
Create Date: 2024-01-24 13:33:10.530725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2e5bf1f9095'
down_revision: Union[str, None] = '710a64380619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.add_column('drivers', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('rating_count', sa.Integer(), nullable=True))
    op.add_column('passengers', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('passengers', sa.Column('rating_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passengers', 'rating_count')
    op.drop_column('passengers', 'rating')
    op.drop_column('drivers', 'rating_count')
    op.drop_column('drivers', 'rating')
    op.create_table('ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passenger_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('driver_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='ratings_trip_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ratings_pkey')
    )
    # ### end Alembic commands ###
